Salsa CI: Unify with similar job logic in MariaDB and Galera packages

diff --git a/debian/salsa-ci.yml b/debian/salsa-ci.yml
--- a/debian/salsa-ci.yml
+++ b/debian/salsa-ci.yml
@@ -1,22 +1,12 @@
-# This is a template from
-# https://salsa.debian.org/salsa-ci-team/pipeline/-/raw/master/recipes/salsa-ci.yml
-#
-# If this pipeline is not running at after committing and pushing this file,
-# ensure that https://salsa.debian.org/%{project_path}/-/settings/ci_cd has in
-# field "CI/CD configuration file" filename "debian/salsa-ci.yml".
-#
-# Feel free disable and enable tests to find a good balance between extensive
-# coverage and having a consistently green pipeline where failures are rare
-# enough that they are always investigated and addressed. For documeenation
-# please read https://salsa.debian.org/salsa-ci-team/pipeline
 ---
+# Include Salsa CI as a base
 include:
   - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml
 
 stages:
   - provisioning
   - build
-  - test
+  - test  # Stage referenced by Salsa CI template reprotest stanza, so must exist
   - upgrade package
   - upgrade package and distro
   - publish  # Stage referenced by Salsa CI template aptly stanza, so must exist even though not used
@@ -47,6 +37,8 @@ build armhf:
 #   rules:
 #     - if: $CI_PROJECT_ROOT_NAMESPACE  == "debian"
 
+# Backports
+
 build bookworm-backports:
   extends: .build-package
   variables:
@@ -59,11 +51,14 @@ build bullseye-backports:
 
 # Debian Stretch too old for debhelper-compat (= 13)
 
+# Define snippets used to construct jobs
+
 .test-prepare-container: &test-prepare-container |
+  # Prepare container for use in CI
   # Change directory to ./debian/output where build artifacts can be found
   cd ${WORKING_DIR}
   # Enable automatic restarts from maint scripts
-  sed -i "s/101/0/g" -i /usr/sbin/policy-rc.d
+  sed -i "s/101/0/g" /usr/sbin/policy-rc.d
   # Fake /sbin/runlevel to avoid warnings of "invoke-rc.d: could not determine current runlevel"
   echo -e '#!/bin/sh\necho "N 5"' > /sbin/runlevel; chmod +x /sbin/runlevel
   # Never stop apt to ask for confirmation, just assume `--yes` all the time
@@ -112,15 +107,19 @@ build bullseye-backports:
   apt-get update -q
 
 .test-enable-sid-repos: &test-enable-sid-repos
-  # Skip this section if already in Sid
+  # If already on Sid, most steps below will be skipped. If upgrading a distro
+  # older than Debian Bookworm, Sid will be enabled only up until March 2025
+  # version as after that a coreutils/util-linux made it impossible to upgrade.
   - |
+    grep PRETTY_NAME /etc/os-release
     if grep -q 'PRETTY_NAME="Debian GNU/Linux trixie/sid"' /etc/os-release
     then
       echo "Already using Sid, no need to enable it"
     else
       # Install tools that may be needed to circumvent issues in the upgrade
       apt-get install -qq --yes --no-install-recommends ca-certificates curl
-      # Replace any old repos with just Sid, and trust blindly as old Debian releases won't have latest Sid in their keyring
+      # Replace any old repos with just Sid
+      rm -vf /etc/apt/sources.list.d/debian.sources
       echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
       # Attempting upgrade from Bullseye or older to Debian Sid is no longer
       # possible in April 2025, as even with all usrmerge workarounds applied
@@ -131,11 +130,13 @@ build bullseye-backports:
       #    util-linux : PreDepends: libc6 (>= 2.41) but 2.38-11 is to be installed
       #
       # Thus, on these older distros, test upgrade only up until the Debian Sid
-      # March 2025 version:
+      # March 2025 version (snapshot chosen just before coreutils/util-linux
+      # gained hard dependencies making upgrades from Bullseye/older impossible):
       if grep -q -E 'bullseye|buster|stretch|jammy|focal' /etc/os-release
       then
         echo 'deb http://snapshot.debian.org/archive/debian/20250315T025205Z sid main' > /etc/apt/sources.list
       fi
+      # Run update to ensure next install command uses latest apt sources
       apt-get update -q
     fi
   # Upgrade minimal stack first
@@ -155,6 +156,9 @@ build bullseye-backports:
   #   *************************************************************************
   # Therefore, an older base-files must be used:
   - |
+    # If apt install failed, it might be due to base-files needing usrmerge.
+    # Attempt workaround using base-files 13.2 (snapshot chosen just before
+    # base-files 13.3 started requiring usrmerge).
     if [ "$APT_STATUS" = "failed" ]
     then
       curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/b/base-files/base-files_13.2_amd64.deb
@@ -168,12 +172,15 @@ build bullseye-backports:
   #   libc6 : Breaks: base-files (< 13.3~) but 13.2 is to be installed
   # Therefore, older libc6 and it's dependency libc6-bin must be used:
   - |
+    # If base-files workaround failed, it might be due to libc6 breaking older
+    # base-files. Attempt workaround using libc6 2.38 (snapshot chosen just
+    # before libc6 2.39 started breaking base-files < 13.3).
     if [ "$BASE_FILES_STATUS" = "failed" ]
     then
       curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc6_2.38-11_amd64.deb
       curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc-bin_2.38-11_amd64.deb
       # Apt version in Jessie does not support 'apt install ./package.deb', use this only for Stretch or newer
-      apt-get install -q --yes --no-install-recommends ./libc6_2.38-11_amd64.deb ./libc-bin_2.38-11_amd64.deb || true
+      apt-get install -q --yes --no-install-recommends ./libc*_*.deb || true
       # Ensure upgrades past 2.38-11 are blocked to avoid failure on usrmerge issue
       apt-mark hold libc6 libc-bin
       apt-get install -q --yes --fix-broken apt
@@ -196,7 +203,7 @@ build bullseye-backports:
       cd - # Back to CI run directory
       find /lib/*/libcrypt.* -ls # Show that new libcrypt is there
       apt-mark unhold libc6 libc-bin
-      apt-get install -q --yes --fix-broken --no-install-recommends ./libc6_2.38-11_amd64.deb ./libc-bin_2.38-11_amd64.deb || true
+      apt-get install -q --yes --fix-broken --no-install-recommends ./libc*_*.deb || true
       # Ensure upgrades past 2.38-11 are blocked to avoid failure on usrmerge issue
       apt-mark hold libc6 libc-bin
       apt-get install -q --yes apt
@@ -239,16 +246,22 @@ build bullseye-backports:
                        grep --only-matching --perl-regex 'of\K /[a-z0-9]+ ')"
       for x in $BASE_DIVERSIONS; do dpkg-divert --no-rename --remove $x; done
     fi
+  # Due to usrmerge, several upgrade attempts are needed until it passes,
+  # with some manual copying of files from /usr/bin/ to /bin/
+  # First 'apt-get upgrade' run likely fails on:
+  #   dpkg (subprocess): unable to execute installed bash package
+  #   post-installation script (/var/lib/dpkg/info/bash.postinst): No such file
+  #   or directory
+  # Second run fails on:
+  #   dpkg (subprocess): unable to execute installed dash package
+  #   post-installation script (/var/lib/dpkg/info/dash.postinst): No such file
+  #   or directory
+  # Third run fails on:
+  #   update-alternatives: error: alternative path /bin/more doesn't exist
+  # Fourth run likely passes.
   - |
-    # First 'apt-get upgrade' run fails on:
-    #   dpkg (subprocess): unable to execute installed bash package post-installation script (/var/lib/dpkg/info/bash.postinst): No such file or directory
-    # Second run fails on:
-    #   dpkg (subprocess): unable to execute installed dash package post-installation script (/var/lib/dpkg/info/dash.postinst): No such file or directory
-    # Third run fails on:
-    #   update-alternatives: error: alternative path /bin/more doesn't exist
-    # Repeat upgrade attempts until passes
     function usrmerge-temp-fix {
-      for x in bash dash sh more cp ln sleep
+      for x in bash cat cp dash ln more sh sleep
       do
         if [ -x /usr/bin/$x ]
         then
@@ -270,6 +283,8 @@ build bullseye-backports:
     done
 
 .test-enable-artifacts-repo: &test-enable-artifacts-repo |
+  # List files so it can be verified from logs that correct artifacts are present
+  find -ls -maxdepth 3
   apt-get install -qq --yes apt-utils
   apt-ftparchive packages . > Packages
   apt-ftparchive release . > Release
@@ -306,8 +321,7 @@ build bullseye-backports:
   - apt-get full-upgrade -qq --yes
   - >
     dpkg -l | grep entr | grep salsaci || {
-      echo "ERROR! Entr was not upgraded from artifacts"
-      find -ls -maxdepth 3
+      echo "ERROR! Entr was not upgraded as expexted to CI version"
       exit 1
     }
 
